### ISSUE TITLE
Missing maven repositories

### ISSUE THREAD

**Issue by phhoef** [Acosix/alfresco-utility#6] opened 2019-12-04 11:42 UTC
I tried building the project and some dependencies could not be resolved.
Adding the `alfresco-public` and `alfresco-public-snapshots` as `repository` and `pluginRepository` solves the problem for me.

```
    <repositories>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
            <repository>
                <id>alfresco-public</id>
                <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
            </repository>
    
            <repository>
                <id>alfresco-public-snapshots</id>
                <url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
                <snapshots>
                    <enabled>true</enabled>
                </snapshots>
            </repository>
    </repositories>

    <pluginRepositories>
            <pluginRepository>
                <id>ossrh</id>
                <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                <snapshots>
                    <enabled>true</enabled>
                </snapshots>
            </pluginRepository>
            <pluginRepository>
                <id>alfresco-public</id>
                <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
            </pluginRepository>
            <pluginRepository>
                <id>alfresco-public-snapshots</id>
                <url>https://artifacts.alfresco.com/nexus/content/groups/public-snapshots</url>
                <snapshots>
                    <enabled>true</enabled>
                </snapshots>
            </pluginRepository>
        </pluginRepositories>
```

**Comment by AFaust** [comment] 2019-12-04 12:38
As mentioned in Skype, I can not yet explain the particular issue. It is kind of strange that you run into this while the Travis CI build works fine - other than my local dev environment, the Travis CI should not be affected by any proxy / mirroring issues that might be shielding me locally from issues like this. E.g. the Travis build for the tag r01000800 succeeded and its log output indicates that it is properly using the alfresco-public / alfresco-public-snapshots repositories inherited from the parent POM, without them having to be explicitly specified.
Can you specify which Maven + JDK versions you are running?

**Comment by phhoef** [comment] 2019-12-04 12:41
Build with Oracle Java 8
 ```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
and Maven
```
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 1.8.0_231, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.1", arch: "x86_64", family: "mac"
```

on macOS 10.15.1 Catalina

**Comment by AFaust** [comment] 2019-12-21 15:39
I have completely reset my local settings, cleared my local Maven repository and built the entire project in the current master state from scratch. My build is using Oracle JDK 8u144 on Windows (I don't have access to an OS X client), and Maven 3.6.0. I have also upgrade my local Maven to 3.6.3 and JDK to 8u231, and tried again. I cannot reproduce this issue at all. I reckon there might have been some (temporary?) network / address resolution or OSSRH server unavailbility issue when resolving the parent POM. This should likely have been logged as part of the build output and may have been missed.
I am closing this issue for the time being - if you can re-run the build, reproduce the same issue and then provide the full Maven build log (ideally using the -X flag), then I can potentially go further with regards to analysing the issue. But right now, I don't see what I can fix in the project which would not lead to redundancy in configuration, as the relevant configuration (repositories) are properly inherited from the parent POM.

**Closed by AFaust** 2019-12-21 15:39 UTC
